on: [push, pull_request]

name: CI

jobs:
  ambuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: '${{ secrets.ATTIC_TOKEN }}'
      - run: nix build .#ambuild

  sdk-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - id: set-matrix
        run: echo "matrix=$(nix eval --json ".#matrix")" | tee $GITHUB_OUTPUT

  sourcemod:
    runs-on: ubuntu-latest
    needs: [sdk-matrix, ambuild]
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.sdk-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: '${{ secrets.ATTIC_TOKEN }}'
      - run: nix build .#packages.${{ matrix.system }}.sourcemods.${{ matrix.sdk }}

  sourcepawn:
    runs-on: ubuntu-latest
    needs: [ambuild]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: '${{ secrets.ATTIC_TOKEN }}'
      - run: nix build .#sourcepawn
      - name: Compile test script
        run: nix build .#buildTestScript